name: jobs name

on:
    push:
        branches:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print Job Name
              run: echo "The job name is ${{ github.job }}" 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Print Job Name
              run: echo "The job name 2 is ${{ github.job }}" 
            