name: job depanding

on:
   push:
     branches:
        - "*"

jobs:
    job-1:
        runs-on: ubuntu-latest
        outputs: 
            name: "muhammed"
        steps:
                - name: Set output
                  run: echo "::set-output name=name::muhammed" # Set the output value
          

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        steps:
            - name: print name
              run: NAME=${{needs.job-1.outputs.name}}

